# ┌1────────────────────┐
# │ Pixel 8 = shiba     │
# │ Pixel 8 Pro = husky │
    DEVICE_CODENAME=shiba
# └─────────────────────┘

# ┌2───────────────────────────────────────────────────────────────────────────────────────────┐
# │ Заполняется по AVB-метаданным оригинального boot.img.                                      │
# │ Их получаем при помощи avbtool.py:                                                         │
# │ https://android.googlesource.com/platform/external/avb/+/refs/heads/main-kernel/avbtool.py │
# │ python3 ./avbtool.py info_image --image [оригинальный boot.img]                            │
# │ Заполняем конфиг ниже исходя из вывода в консоли.                                          │
# │ Заполняйте поля с соответствующим префиксом, исходя от типа прошивки.                      │
    STABLE_rollback_index=1772668800
    STABLE_salt=8c941d4cd5f529746ce013e4ff9dbb21fd3f12f0c260848fcaa2ce30068c6562
    STABLE_os_version=16
    STABLE_fingerprint=google/${DEVICE_CODENAME}/${DEVICE_CODENAME}:16/CP1A.260305.018/14887507:user/release-keys
    STABLE_security_patch=2026-03-05

    BETA_rollback_index=1772668800
    BETA_salt=6caae4112961def27eeacd6573fb2417a926db7e6619a8aec1f8c3cf70a70ade
    BETA_os_version=17
    BETA_fingerprint=google/${DEVICE_CODENAME}_beta/${DEVICE_CODENAME}:17/CP21.260306.017/15063635:user/release-keys
    BETA_security_patch=2026-03-05
# └────────────────────────────────────────────────────────────────────────────────────────────┘

# ┌3─────────────────────────────────────────────────────────────┐
# │ МЕНЯТЬ ТОЛЬКО В СЛУЧАЕ                                       │
# │ ОБНОВЛЕНИЯ ПАТЧЕЙ В ПАПКЕ patches                            │
# │ Патчи взяты с: https://github.com/WildKernels/kernel_patches │
    KSU_NEXT_COMMIT="cb559258dd04cd480e2bd8e0397b63c256c7b0d0"
    SUSFS_COMMIT="fd67b314b85dbacf5b37580b6ebd531d39f6cf8b"
    KSU_NEXT_PATCHES=(
      "fix_Kbuild.patch"
      "fix_kernel_umount.c.patch"
      "fix_ksu.c.patch"
      "fix_ksud.c.patch"
      "fix_Makefile.patch"
      "fix_setuid_hook.c.patch"
      "fix_sucompat.c.patch"
      "fix_sucompat.h.patch"
      "fix_supercalls.c.patch"
      "ksu_toolkit.patch"
      "overwrite_hook_mode.patch"
    )
# └──────────────────────────────────────────────────────────────┘


# ┌4─────────────────────────────────────────────────────────────────┐
# │ Определяет ветку клонируемую с:                                  │
# │ https://android.googlesource.com/kernel/common/+refs             │
# │ В makefile каждой ветки, который находится в корне репозитория,  │
# │ всегда указана нумерация ядра.                                   │
# │ Выбирается в соответствии с версией ядра установленной прошивки. │
    STABLE_BRANCH="android14-6.1-2025-09"
    BETA_BRANCH="android14-6.1-2025-12"
# └──────────────────────────────────────────────────────────────────┘

# ┌5─────────────────────────────────────────────┐
# │ Содержит драйвера, инструменты сборки и т.д. │
# │ Ссылка на репозиторий:                       │
# │ https://gitlab.com/grapheneos/kernel_pixel   │
    PIXEL_TAG="2026040300"
    PIXEL_COMMIT="3472166edff4c6c0e76fc5f677f2422a7d90bdc2"
# └──────────────────────────────────────────────┘